### ISSUE TITLE
Cannot use call_command

### ISSUE THREAD

**Issue by clems71** [mbraak/django-docopt-command#24]
I was writing a test case for a custom command and the DocOptCommand subclassed classes does not support the django.core.management.call_command function. The called command uses the ./manage.py test args, not the args provided in call_command.

**Comment by mbraak** [comment]
The ``call_command`` function from Django does not work because ``DocOptCommand`` works a bit different than standard django commands.

Perhaps you can use the ``call_docopt_command`` function. It's implemented in the [tests](https://github.com/mbraak/django-docopt-command/blob/master/testproject/docopt_example/tests.py).
